### ISSUE TITLE
Need to Improve Comment Color

### ISSUE THREAD

**Issue by iamibrahimriaz** [WordPress/wpcs-docs#129]
If Good, Better comments are green color & Bad, Not Acceptable comments are in red color. Also Not bad & it have better solution but acceptable comments are in yellow color. Then it will increase readability & understandability of docs.

![image](https://github.com/WordPress/wpcs-docs/assets/99108560/8157c3df-c968-426b-81a5-cd7b6681a063)

**Comment by dingo-d** [comment]
I think this is the default of the code block that is used (probably some JS lib). Since these are code comments, they are the same color and it would be really really hard to modify these.

They are mimicking how your code editor behaves, and your code editor doesn't distinguish 'good' from 'bad' comment.

**Comment by jrfnl** [comment]
I agree with @dingo-d.

Additionally, I think the suggestion would actually decrease readability as green/red coloured background for the code will give people the impression it is a code diff/patch, which none of these examples are.

Also relying on colours alone to convey meaning is really bad practice accessibility-wise, so I'd very much discourage it.

**Comment by GaryJones** [comment]
> relying on colours alone to convey meaning is really bad practice accessibility-wise

Agreed, though the suggestion in this case isn;t suggesting that, as the comment words themselves are also different :-)

Still bad for accessibility though (even if it were possible) - those with certain types of colour blindness can mix up red and green, users may have custom CSS applied that changes the background colour, and some cultures may have red = good and green = bad.
