### ISSUE TITLE
Link Issue in about license page

### ISSUE THREAD

**Issue by anik** [WordPress/wpcs-docs#30]
Page:-
https://wordpress.org/about/license/

Screenshot-
http://prntscr.com/qlrdmn

ISSUE 1:
Replace this link-
https://drupal.org/licensing/faq/
With
https://www.drupal.org/about/licensing

ISSUE 2:
Replace this link-
https://www.s9y.org/
With
https://docs.s9y.org/

ISSUE 3:
This link is not working at all.
http://habariproject.org/en/

**Comment by ntwb** [comment]
Thanks @anik, but sorry to make this confusing, but this issue needs to be reported to https://meta.trac.wordpress.org/ 

This repo here is only for documentation issues relating to the WordPress Coding Standards at https://developer.wordpress.org/coding-standards/

**Comment by anik** [comment]
Ok thanks
