### ISSUE TITLE
"No Shorthand PHP Tags" section of PHP Coding Standards

### ISSUE THREAD

**Issue by bizanimesh** [WordPress/wpcs-docs#38]
The below example of **Correct** and **Incorrect** is not available in [No Shorthand PHP Tags section of PHP Coding Standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#no-shorthand-php-tags).

**Correct:**

```
<?php ... ?>
<?php echo $var; ?>
```

**Incorrect:**

```
<? ... ?>
<?= $var ?>
```

**Comment by diogoca** [comment]
I checked  that wordpress-coding-standards/php.md and it's fine. May be some escape function on backend source of developer.wordpress.org that's making print empty.

**Comment by bizanimesh** [comment]
Hi Diogo,

Yes, I have also checked wordpress-coding-standards/php.md and there all
things are fine.

So how this problem would be solved?

**Comment by bizanimesh** [comment]
Hi Diogo,

Yes, I have also checked wordpress-coding-standards/php.md and all
things are fine there.

So how [this problem](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#no-shorthand-php-tags)  would be solved?

Do I need to contact any team on Slack?

**Comment by ntwb** [comment]
Ugh, the #39 PR did not resolve this:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/1016458/88041459-c5591b80-cb8d-11ea-8d26-553e5c431cca.png">

It's not blank like previously it was, nevertheless will have to investigate further

Most likely. meta ticket will need to be created to add support to the markdown parser to account for this, will follow up with that shortly

**Comment by coffee2code** [comment]
Meant to follow up with this yesterday. Not sure if the ticket closure is a result of this or not, but I closed out this issue as reported on meta.trac in [#meta5346](https://meta.trac.wordpress.org/ticket/5346).

Here's what I wrote as a comment there that is relevant here:

> This is an outstanding issue in general that for which the likely culprit is the SyntaxHighlighter Evolved plugin's handling of code shortcodes. Its block handling is superior and doesn't have this issue, but in this case the Code Standards Handbook is fully imported from GitHub, and thus originates as text in a Markdown format.
> 
> I believe the issue would be resolved if the source documents avoided the use of code shortcodes (e.g. `[php]`, `[html]`, `[css]`, `[javascript]`, or `[code]`) and instead used triple backticks (with optional language hinting) _**without pre-encoding**_, e.g.
> 
````
```html
<div class="hfeed">
         <article id="post-" class="">
             <!-- ... -->
         </article>
</div>
```
````
> The Block Editor Handbook is also imported from GitHub and uses backticks (e.g. [a source .md file](https://github.com/WordPress/gutenberg/edit/master/docs/designers-developers/developers/themes/theme-json.md) and [its resultant handbook page](https://developer.wordpress.org/block-editor/developers/themes/theme-json/)) which could be used for reference.
