### ISSUE TITLE
Single Quotes using `&#039;` instead of `'`

### ISSUE THREAD

**Issue by ntwb** [WordPress/wpcs-docs#46]
A follow up to #44/45

https://developer.wordpress.org/coding-standards/wordpress-coding-standards/html/#quotes

<img width="667" alt="image" src="https://user-images.githubusercontent.com/1016458/95695334-29b5e380-0c82-11eb-890d-739dc4018c29.png">

Source: https://github.com/WordPress/wpcs-docs/blob/master/wordpress-coding-standards/html.md#L46-L49

```html
<input type="text" name="email" disabled="disabled" />
<input type='text' name='email' disabled='disabled' />
```

This can be observered on the following pages (possibly others also)

- https://developer.wordpress.org/coding-standards/inline-documentation-standards/php   
- https://developer.wordpress.org/coding-standards/inline-documentation-standards/javascript
- https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php
- https://developer.wordpress.org/coding-standards/wordpress-coding-standards/html

cc @coffee2code

**Comment by jrfnl** [comment]
Confirmed. Is this a bug in the markdown parser used in the conversion ? Doc source looks ok (at least for the example above).

I'm also noticing another issue: numbered lists containing code samples and such seem to be loosing their consecutive numbering as can be observed here: https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#description-formerly-long-description

Looking at the source, if we're talking proper markdown, the rest of the paragraph which is part of the number list item should probably be indented, which it currently isn't. Not sure if that will fix it though, but worth a try.

@ntwb Should I open a new issue for this ?

**Comment by coffee2code** [comment]
> Confirmed. Is this a bug in the markdown parser used in the conversion ? Doc source looks ok (at least for the example above).

The source is fine. There's a double-encoding issue going on somewhere that I haven't had a chance to investigate yet. However, as of [r10366-meta](https://meta.trac.wordpress.org/changeset/10366), I've extended the double-encoding fix implemented for [#meta5346](https://meta.trac.wordpress.org/ticket/5346) to include single-quotes. The pages linked above all look proper now.

> Looking at the source, if we're talking proper markdown, the rest of the paragraph which is part of the number list item should probably be indented, which it currently isn't. Not sure if that will fix it though, but worth a try.

I'd certainly suggest giving that a try first. However, I wouldn't be surprised if the Markdown importer won't recognize list items containing multiple space-separated blocks. In that case, maybe each list item could be the start of a new nested heading (in this case `h5`).

**Comment by ntwb** [comment]
Thanks, looking good 👌🏼

@jrfnl Now that the above is in, a new issue sounds good to track this.

Possibly testing it in this file, I created this file as a bit of a playground to test these types of issues to test the imported markdown https://github.com/WordPress/wpcs-docs/blob/master/styleguide.md
