### ISSUE TITLE
Removed link to WordPress PHP coding standards Page

### ISSUE THREAD

**Issue by SavPhill** [WordPress/wpcs-docs#78]
In the Javascript Coding Standards page of the Handbook:
https://developer.wordpress.org/coding-standards/wordpress-coding-standards/javascript/#naming-conventions

There is a link to the WordPress PHP coding standards page with a #naming-conventions anchor:

https://make.wordpress.org/core/handbook/coding-standards/php/#naming-conventions

This page does not have a naming conventions section or anchor. Therefore my PR is to remove the link altogether as it is not useful.

**Comment by jrfnl** [comment]
@SavPhill I agree that the link is wrong, but it shouldn't be removed. It should be fixed to point to the correct page: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#naming-conventions
