### ISSUE TITLE
Restructuring the PHP coding standards

### ISSUE THREAD

**Issue by dingo-d** [WordPress/wpcs-docs#93]
## Introduction

Given that the [PER coding styles](https://github.com/php-fig/per-coding-style/releases/tag/1.0.0) were released 8 days ago, and we've made progress in updating the coding standards a bit in the last few months - markdown updates, update some phrasing, removed outdated references, updated examples  (still pending in PR #92), I thought that it wouldn't be a bad idea to give some proper structure to the PHP WordPress Coding Standards (PHP WPCS).

By structure, I mean grouping the currently disjointed parts of the CS into some logical groups, like what PER standards (which are just PSR-12 standards at the moment) are doing.

## Current status

Currently, we have the following sections

```md
Single and Double Quotes
Indentation
Brace Style
Use `elseif`, not `else if`
Declaring Arrays
Closures (Anonymous Functions)
Multiline Function Calls
Regular Expressions
Opening and Closing PHP Tags
No Shorthand PHP Tags
Remove Trailing Spaces
Space Usage
Formatting SQL statements
Database Queries
Naming Conventions
Only one object structure (class/interface/trait) per file
Self-Explanatory Flag Values for Function Arguments
Interpolation for Naming Dynamic Hooks
Ternary Operator
Yoda Conditions
Clever Code
Error Control Operator `@`
Don't `extract()`
```

The PER style has the following main sections:

```md
Overview
General
Declare Statements, Namespace, and Import Statements
Classes, Properties, and Methods
Control Structures
Operators
Closures
Anonymous Classes
```

With subsections it looks like this:

```md
2. General
  2.1 Basic Coding Standard
  2.2 Files
  2.3 Lines
  2.4 Indenting
  2.5 Keywords and Types
3. Declare Statements, Namespace, and Import Statements
4. Classes, Properties, and Methods
  4.1 Extends and Implements
  4.2 Using traits
  4.3 Properties and Constants
  4.4 Methods and Functions
  4.5 Method and Function Arguments
  4.6 abstract, final, and static
  4.7 Method and Function Calls
5. Control Structures
  5.1 if, elseif, else
  5.2 switch, case
  5.3 while, do while
  5.4 for
  5.5 foreach
  5.6 try, catch, finally
6. Operators
  6.1. Unary operators
  6.2. Binary operators
  6.3. Ternary operators
7. Closures
8. Anonymous Classes
```

which is a lot more structured and clear in my opinion.

## Proposal

The proposal is to have the following grouping in the PHP WPCS:

```md
General
  Opening and Closing PHP Tags
  No Shorthand PHP Tags
  Brace Style
  Single and Double Quotes
  Multiline Function Calls

Naming and declarations
  Naming Conventions
  Interpolation for Naming Dynamic Hooks
  Declaring Arrays

Control structures
  Use `elseif`, not `else if`

Whitespace
  Space Usage
  Indentation
  Remove Trailing Spaces

Object-oriented programming
  Only one object structure (class/interface/trait) per file

Operators
  Ternary Operator

Database
  Database Queries
  Formatting SQL statements

Closures (Anonymous Functions)

Best recommendations
  Regular Expressions
  Self-Explanatory Flag Values for Function Arguments
  Clever Code
  Yoda Conditions
  Error Control Operator `@`
  Don't `extract()`
```

This will give a better structure - knowing where things should be located will help find what you need quickly, as well as prepare for the addition of more modern PHP constructs defined in the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/).

The content inside the existing standards **will stay the same**, so this is just a grouping change (adding new chapters and putting the other parts inside correct chapters).

Please let me know if you think that some sections belong in other chapters, or if you think that the chapters themselves need a better name.

CC @GaryJones @ntwb @jrfnl

**Comment by dingo-d** [comment]
I've had a call with Juliette and she pointed out some inconsistencies in the proposed structure. I've taken it another look, and I came up with a new proposal:

~~~text
General
  Opening and closing PHP tags
  No shorthand PHP tags
  Single and double quotes

Naming
  Naming conventions
  Interpolation for naming dynamic hooks

Whitespace
  Space usage
  Indentation
  Remove trailing spaces

Formatting
  Brace style
  Declaring arrays
  Multiline function calls

Object-Oriented Programming
  Only one object structure (class/interface/trait) per file

Control Structures
  Use `elseif`, not `else if`
  Yoda conditions

Operators
  Ternary operator
  Error control operator `@`

Closures (Anonymous Functions)

Database
  Database queries
  Formatting SQL statements

Best Recommendations
  Self-explanatory flag values for function arguments
  Clever code
  Regular expressions
  Don't `extract()`
~~~

I still wouldn't mix the closures with the Formatting part, mostly because that part just suggests what they can be used for and that they shouldn't be used as a callback for hooks.

I think that General, Naming, Whitespace, and Formatting should be at the top because they are more oriented towards the general rules and practices for writing code.
After that, we can more or less follow how PER standards are structuring the code: OOP (intention is to add modern additions once we create PRs for them), Control Structures, Operators, and Closures.
The DB and Best Recommendations would be at the end because they are sort of miscellaneous.

I've also decapitalized the subchapter names. Not sure what is the rule about naming chapters/subchapters. I noticed that PER capitalizes certain words, and certain words are left uncapitalized, so if anybody has any kind of recommendation here I'm all for it 🙂

**Comment by jrfnl** [comment]
> I still wouldn't mix the closures with the Formatting part, mostly because that part just suggests what they can be used for and that they shouldn't be used as a callback for hooks.

If that's all that's being said about closures (no formatting rules), maybe it should actually be under "Best Practice Recommendations" ?

> I've also decapitalized the subchapter names. Not sure what is the rule about naming chapters/subchapters.

I think these kind of headers, in general, mostly used [Title Case](https://en.wikipedia.org/wiki/Title_case). There are [converter tools](https://titlecaseconverter.com/) available to help with that.

**Comment by dingo-d** [comment]
> If that's all that's being said about closures (no formatting rules), maybe it should actually be under "Best Practice Recommendations" ?

Hmmm, that's not a bad suggestion (as usual 😄). I agree we can then put them in the Best Recommendations.

> I think these kind of headers, in general, mostly used [Title Case](https://en.wikipedia.org/wiki/Title_case). There are [converter tools](https://titlecaseconverter.com/) available to help with that.

Thanks, wasn't aware that there were some rules about that. In that case, after reformatting the structure would be:

~~~text
General
  Opening and Closing PHP Tags
  No Shorthand PHP Tags
  Single and Double Quotes

Naming
  Naming Conventions
  Interpolation for Naming Dynamic Hooks

Whitespace
  Space Usage
  Indentation
  Remove Trailing Spaces

Formatting
  Brace Style
  Declaring Arrays
  Multiline Function Calls

Object-Oriented Programming
  Only One Object Structure (Class/Interface/Trait) per File

Control Structures
  Use `elseif`, Not `else if`
  Yoda Conditions

Operators
  Ternary Operator
  Error Control Operator `@`

Database
  Database Queries
  Formatting SQL Statements

Best Recommendations
  Self-Explanatory Flag Values for Function Arguments
  Clever Code
  Closures (Anonymous Functions)
  Regular Expressions
  Don't `extract()`
~~~

**Comment by jrfnl** [comment]
`Best Recommendation` should probably still be changed to either `Best Practices`, `Best Practice Recommendations` or to `Recommendations`, but other than that, this looks good to me, with the express provision you made earlier for the new standards to be included:

> After that, we can more or less follow how PER standards are structuring the code: OOP (intention is to add modern additions once we create PRs for them), Control Structures, Operators, and Closures.

**Comment by dingo-d** [comment]
I usually avoid the phrase `Best Practices` because it's super subjective. And the term 'best practices' suggests that they are universally best.
For instance, for specific projects where I don't want anybody to unhook my callback, I'll explicitly use a closure (even if that's not a guarantee that somebody afterward won't come and unhook it, it's just going to take them a long time to do so 😅).

I'd opt for `Best Practice Recommendations` as a middle ground 👍🏼 😄

**Comment by jrfnl** [comment]
I get your objection. I'm perfectly fine with just naming it `Recommendations` if you prefer.
